### ISSUE TITLE
Add language support

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/luatex-harfbuzz#4]

**Comment by khaledhosny** [comment]
I think this should use the hyphenation language by default, but there should also be a way to specify a language for shaping independent of hyphenation language for the case you want OpenType features for a specific language and hyphenation for another e.g. if the text is in Macedonian but the font has only Serbian language, one will want to use Macedonian hyphenation but shape the font with Serbian language which will provide localized glyph alternates suitable for Macedonian (this example might not be exactly correct, but the general idea exists).

**Comment by deepakjois** [comment]
Closed in favor of deepakjois/ufylayout#4
